name: weather_app
description: A weather App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  dio: ^5.3.3
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  geolocator: ^10.0.1
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/