// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW3WOnb3XtVYbrpK-CwW3YxOxvu39ppF8',
    appId: '1:210345626252:web:b23aa08876efdf786449a9',
    messagingSenderId: '210345626252',
    projectId: 'weather-app-86bda',
    authDomain: 'weather-app-86bda.firebaseapp.com',
    storageBucket: 'weather-app-86bda.appspot.com',
    measurementId: 'G-8PQ4GET3MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwk3fdLbj24ItI3JUrJ0oGDEnpUHEqM7o',
    appId: '1:210345626252:android:496e03d6c6e214f86449a9',
    messagingSenderId: '210345626252',
    projectId: 'weather-app-86bda',
    storageBucket: 'weather-app-86bda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyLGcNU_oBKDL_dAbyi2JmqtyMpKWv8kA',
    appId: '1:210345626252:ios:d66451e90d951f526449a9',
    messagingSenderId: '210345626252',
    projectId: 'weather-app-86bda',
    storageBucket: 'weather-app-86bda.appspot.com',
    iosBundleId: 'surya.oktana.weatherApp',
  );
}
